agisent_dir=c:\agisent

libs = support \
	api \
	conversion \
	datagen \
	incidentReporting \
	lex \
	onboarding \
	reportActivity \
	reportRacialProfilingCFS \
	reportRacialProfilingCitations \
	scibrs \
	tibrs \

api_sources = \
	api.fgl

conversion_sources = \
	conversion.fgl

datagen_sources = \
	datagen.fgl

incidentReporting_sources = \
	incidentReporting.fgl

lex_sources = \
	lex.fgl

onboarding_sources = \
	onboarding.fgl

reportActivity_sources = \
	reportActivity.fgl

reportRacialProfilingCFS_sources = \
	reportRacialProfilingCFS.fgl

reportRacialProfilingCitations_sources = \
	reportRacialProfilingCitations.fgl

scibrs_sources = \
	scibrs.fgl

tibrs_sources = \
	tibrs.fgl

support_sources = support.fgl \
	queue.fgl \
	agency.fgl \
	misc.fgl \
	entity.fgl \
	aliases.fgl \
	id.fgl \
	relations.fgl \
	contacts.fgl \
	marks.fgl \
	vehicles.fgl \
	person.fgl \
	organizations.fgl \
	location.fgl \
	category.fgl \
	call.fgl \
	user.fgl \
	documents.fgl \
	trans.fgl \
	units.fgl \
	schedule.fgl \
	case.fgl \
	incident.fgl \
	party.fgl \
	property.fgl \
	action.fgl \
	mail.fgl \
	localLex.fgl \
	legal.fgl \
	systemAccess.fgl \
	naics.fgl \
	regiondata.fgl \
	prodocs2.fgl \
	citations.fgl \
	warrants.fgl \
	barcode.fgl \
	accounting.fgl \
	cad.fgl \
	warnings.fgl \
	expungement.fgl \
	personnel.fgl \
	desktop.fgl \
	fusion.fgl \
	filesys.fgl \
	evidence.fgl \
	arrest.fgl \
	drugs.fgl \
	reports.fgl \
	message.fgl \
	victimrights.fgl \
	account.fgl \
	foia.fgl \
	court.fgl \
	vfs.fgl \
	watch.fgl \
	civil.fgl \
	legacy.fgl \
	security.fgl \
	training.fgl \
	procase.fgl \
	nibrs.fgl \
	stats.fgl \
	college.fgl \

include makefile.inc

